name: Setup-ECS-Infrastructure
description: Workflow to setup ECS Infrastructure for an application

inputs:
  cf_stack_name:
    description: Cloudformation Stack Name
    required: true
  cf_template_file_path:
    description: Location of the cloudformation file to deploy
    required: true
  cf_template_file_name:
    description: Cloudformation file name
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create ECS Service Infrastructure
      shell: bash
      working-directory: cdk
      run: |
        yarn
        yarn cdk synth -q -o ${{ inputs.cf_template_file_path }}
        aws cloudformation create-stack \
          --capabilities CAPABILITY_IAM \
          --stack-name ${{ inputs.cf_stack_name }} \
          --template-body file://${{ inputs.cf_template_file_path }}/${{ inputs.cf_template_file_name }}
