name: Setup-ECS-Infrastructure
description: Workflow to setup ECS Infrastructure for an application

inputs:
  cf_stack_name:
    description: Cloudformation Stack Name
    required: true
  cf_template_file_path:
    description: Location of the cloudformation file to deploy
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Create ECS Service Infrastructure
      shell: bash
      run: |
        echo path is : ${{ inputs.cf_template_file_path }}
        pwd
        @aws cloudformation create-stack \
          --stack-name $(REPOSITORY_NAME)-ecs-infra \
          --template-body file://${{ inputs.cf_template_file_path }}
